import type { CEFRLevel } from './types'

// Словарь и темы для каждого уровня
export const VOCABULARY_BY_LEVEL: Record<CEFRLevel, Array<{ spanish: string; russian: string; topic: string }>> = {
  'Базовый': [
    { spanish: 'Hola', russian: 'Привет', topic: 'Приветствия' },
    { spanish: 'Buenos días', russian: 'Доброе утро', topic: 'Приветствия' },
    { spanish: 'Buenas tardes', russian: 'Добрый день', topic: 'Приветствия' },
    { spanish: 'Buenas noches', russian: 'Добрый вечер/Спокойной ночи', topic: 'Приветствия' },
    { spanish: 'Adiós', russian: 'До свидания', topic: 'Приветствия' },
    { spanish: 'Hasta luego', russian: 'До скорого', topic: 'Приветствия' },
    { spanish: 'Por favor', russian: 'Пожалуйста (просьба)', topic: 'Вежливость' },
    { spanish: 'Gracias', russian: 'Спасибо', topic: 'Вежливость' },
    { spanish: 'De nada', russian: 'Пожалуйста (ответ)', topic: 'Вежливость' },
    { spanish: 'Perdón', russian: 'Извините', topic: 'Вежливость' },
    { spanish: 'Sí', russian: 'Да', topic: 'Базовое' },
    { spanish: 'No', russian: 'Нет', topic: 'Базовое' },
    { spanish: '¿Cómo estás?', russian: 'Как дела?', topic: 'Вопросы' },
    { spanish: '¿Qué tal?', russian: 'Как дела?', topic: 'Вопросы' },
    { spanish: 'Bien', russian: 'Хорошо', topic: 'Ответы' },
    { spanish: 'Mal', russian: 'Плохо', topic: 'Ответы' },
    { spanish: 'Uno', russian: 'Один', topic: 'Числа' },
    { spanish: 'Dos', russian: 'Два', topic: 'Числа' },
    { spanish: 'Tres', russian: 'Три', topic: 'Числа' },
    { spanish: 'Cuatro', russian: 'Четыре', topic: 'Числа' },
    { spanish: 'Cinco', russian: 'Пять', topic: 'Числа' },
    { spanish: 'Rojo', russian: 'Красный', topic: 'Цвета' },
    { spanish: 'Azul', russian: 'Синий', topic: 'Цвета' },
    { spanish: 'Verde', russian: 'Зелёный', topic: 'Цвета' },
    { spanish: 'Amarillo', russian: 'Жёлтый', topic: 'Цвета' },
    { spanish: 'El padre', russian: 'Отец', topic: 'Семья' },
    { spanish: 'La madre', russian: 'Мать', topic: 'Семья' },
    { spanish: 'El hermano', russian: 'Брат', topic: 'Семья' },
    { spanish: 'La hermana', russian: 'Сестра', topic: 'Семья' },
    { spanish: 'El hijo', russian: 'Сын', topic: 'Семья' },
    { spanish: 'La casa', russian: 'Дом', topic: 'Жильё' },
    { spanish: 'El perro', russian: 'Собака', topic: 'Животные' },
    { spanish: 'El gato', russian: 'Кошка', topic: 'Животные' },
    { spanish: 'El agua', russian: 'Вода', topic: 'Еда' },
    { spanish: 'El pan', russian: 'Хлеб', topic: 'Еда' },
  ],
  'A1': [
    { spanish: 'Yo soy', russian: 'Я есть/являюсь', topic: 'Глагол ser' },
    { spanish: 'Tú eres', russian: 'Ты есть/являешься', topic: 'Глагол ser' },
    { spanish: 'Él/Ella es', russian: 'Он/Она есть/является', topic: 'Глагол ser' },
    { spanish: 'Nosotros somos', russian: 'Мы есть/являемся', topic: 'Глагол ser' },
    { spanish: 'Vosotros sois', russian: 'Вы есть/являетесь', topic: 'Глагол ser' },
    { spanish: 'Ellos son', russian: 'Они есть/являются', topic: 'Глагол ser' },
    { spanish: 'Estoy', russian: 'Я нахожусь/чувствую себя', topic: 'Глагол estar' },
    { spanish: 'Estás', russian: 'Ты находишься', topic: 'Глагол estar' },
    { spanish: 'Está', russian: 'Он/Она находится', topic: 'Глагол estar' },
    { spanish: 'Hablar', russian: 'Говорить', topic: 'Глаголы -ar' },
    { spanish: 'Comer', russian: 'Есть/Кушать', topic: 'Глаголы -er' },
    { spanish: 'Vivir', russian: 'Жить', topic: 'Глаголы -ir' },
    { spanish: 'Trabajar', russian: 'Работать', topic: 'Работа' },
    { spanish: 'Estudiar', russian: 'Учиться', topic: 'Учёба' },
    { spanish: 'La familia', russian: 'Семья', topic: 'Семья' },
    { spanish: 'El abuelo', russian: 'Дедушка', topic: 'Семья' },
    { spanish: 'La abuela', russian: 'Бабушка', topic: 'Семья' },
    { spanish: 'El tío', russian: 'Дядя', topic: 'Семья' },
    { spanish: 'La tía', russian: 'Тётя', topic: 'Семья' },
    { spanish: 'El primo', russian: 'Двоюродный брат', topic: 'Семья' },
    { spanish: 'La cocina', russian: 'Кухня', topic: 'Дом' },
    { spanish: 'El dormitorio', russian: 'Спальня', topic: 'Дом' },
    { spanish: 'El baño', russian: 'Ванная', topic: 'Дом' },
    { spanish: 'El salón', russian: 'Гостиная', topic: 'Дом' },
    { spanish: 'La mesa', russian: 'Стол', topic: 'Мебель' },
    { spanish: 'La silla', russian: 'Стул', topic: 'Мебель' },
    { spanish: 'La cama', russian: 'Кровать', topic: 'Мебель' },
    { spanish: 'El sofá', russian: 'Диван', topic: 'Мебель' },
    { spanish: 'El restaurante', russian: 'Ресторан', topic: 'Места' },
    { spanish: 'El supermercado', russian: 'Супермаркет', topic: 'Места' },
    { spanish: 'La escuela', russian: 'Школа', topic: 'Места' },
    { spanish: 'El hospital', russian: 'Больница', topic: 'Места' },
    { spanish: 'El profesor', russian: 'Учитель', topic: 'Профессии' },
    { spanish: 'El médico', russian: 'Врач', topic: 'Профессии' },
    { spanish: 'El cocinero', russian: 'Повар', topic: 'Профессии' },
  ],
  'A2': [
    { spanish: 'He comido', russian: 'Я поел (недавно)', topic: 'Pretérito Perfecto' },
    { spanish: 'Has hablado', russian: 'Ты говорил', topic: 'Pretérito Perfecto' },
    { spanish: 'Ha vivido', russian: 'Он/Она жил(а)', topic: 'Pretérito Perfecto' },
    { spanish: 'Hemos estudiado', russian: 'Мы учились', topic: 'Pretérito Perfecto' },
    { spanish: 'Comí', russian: 'Я поел (прошлое)', topic: 'Pretérito Indefinido' },
    { spanish: 'Hablaste', russian: 'Ты говорил', topic: 'Pretérito Indefinido' },
    { spanish: 'Vivió', russian: 'Он/Она жил(а)', topic: 'Pretérito Indefinido' },
    { spanish: 'Más grande que', russian: 'Больше чем', topic: 'Сравнение' },
    { spanish: 'Menos interesante que', russian: 'Менее интересный чем', topic: 'Сравнение' },
    { spanish: 'Tan alto como', russian: 'Такой же высокий как', topic: 'Сравнение' },
    { spanish: 'El mejor', russian: 'Самый лучший', topic: 'Превосходная степень' },
    { spanish: 'El peor', russian: 'Самый худший', topic: 'Превосходная степень' },
    { spanish: 'La ropa', russian: 'Одежда', topic: 'Одежда' },
    { spanish: 'La camisa', russian: 'Рубашка', topic: 'Одежда' },
    { spanish: 'Los pantalones', russian: 'Брюки', topic: 'Одежда' },
    { spanish: 'El vestido', russian: 'Платье', topic: 'Одежда' },
    { spanish: 'Los zapatos', russian: 'Туфли', topic: 'Одежда' },
    { spanish: 'El avión', russian: 'Самолёт', topic: 'Транспорт' },
    { spanish: 'El tren', russian: 'Поезд', topic: 'Транспорт' },
    { spanish: 'El autobús', russian: 'Автобус', topic: 'Транспорт' },
    { spanish: 'El coche', russian: 'Машина', topic: 'Транспорт' },
    { spanish: 'La bicicleta', russian: 'Велосипед', topic: 'Транспорт' },
    { spanish: 'El hotel', russian: 'Отель', topic: 'Путешествия' },
    { spanish: 'El aeropuerto', russian: 'Аэропорт', topic: 'Путешествия' },
    { spanish: 'La estación', russian: 'Вокзал', topic: 'Путешествия' },
    { spanish: 'El billete', russian: 'Билет', topic: 'Путешествия' },
    { spanish: 'La maleta', russian: 'Чемодан', topic: 'Путешествия' },
    { spanish: 'El tiempo', russian: 'Погода/Время', topic: 'Погода' },
    { spanish: 'Hace sol', russian: 'Солнечно', topic: 'Погода' },
    { spanish: 'Hace frío', russian: 'Холодно', topic: 'Погода' },
    { spanish: 'Hace calor', russian: 'Жарко', topic: 'Погода' },
    { spanish: 'Llueve', russian: 'Идёт дождь', topic: 'Погода' },
    { spanish: 'Nieva', russian: 'Идёт снег', topic: 'Погода' },
  ],
  'B1': [
    { spanish: 'Comía', russian: 'Я ел (регулярно в прошлом)', topic: 'Pretérito Imperfecto' },
    { spanish: 'Hablabas', russian: 'Ты говорил', topic: 'Pretérito Imperfecto' },
    { spanish: 'Vivía', russian: 'Он/Она жил(а)', topic: 'Pretérito Imperfecto' },
    { spanish: 'Comeré', russian: 'Я буду есть', topic: 'Futuro Simple' },
    { spanish: 'Hablarás', russian: 'Ты будешь говорить', topic: 'Futuro Simple' },
    { spanish: 'Vivirá', russian: 'Он/Она будет жить', topic: 'Futuro Simple' },
    { spanish: 'Que yo coma', russian: 'Чтобы я ел', topic: 'Subjuntivo Presente' },
    { spanish: 'Que tú hables', russian: 'Чтобы ты говорил', topic: 'Subjuntivo Presente' },
    { spanish: 'Que él viva', russian: 'Чтобы он жил', topic: 'Subjuntivo Presente' },
    { spanish: 'Es importante que', russian: 'Важно, чтобы', topic: 'Subjuntivo' },
    { spanish: 'Es necesario que', russian: 'Необходимо, чтобы', topic: 'Subjuntivo' },
    { spanish: 'Espero que', russian: 'Надеюсь, что', topic: 'Subjuntivo' },
    { spanish: 'Dudo que', russian: 'Сомневаюсь, что', topic: 'Subjuntivo' },
    { spanish: 'La política', russian: 'Политика', topic: 'Общество' },
    { spanish: 'La economía', russian: 'Экономика', topic: 'Общество' },
    { spanish: 'La cultura', russian: 'Культура', topic: 'Общество' },
    { spanish: 'El medio ambiente', russian: 'Окружающая среда', topic: 'Экология' },
    { spanish: 'La contaminación', russian: 'Загрязнение', topic: 'Экология' },
    { spanish: 'Reciclar', russian: 'Перерабатывать', topic: 'Экология' },
    { spanish: 'El empleo', russian: 'Занятость', topic: 'Работа' },
    { spanish: 'La entrevista', russian: 'Собеседование', topic: 'Работа' },
    { spanish: 'El currículum', russian: 'Резюме', topic: 'Работа' },
    { spanish: 'La tecnología', russian: 'Технология', topic: 'Технологии' },
    { spanish: 'El ordenador', russian: 'Компьютер', topic: 'Технологии' },
    { spanish: 'El móvil', russian: 'Мобильный телефон', topic: 'Технологии' },
    { spanish: 'Internet', russian: 'Интернет', topic: 'Технологии' },
  ],
  'B2': [
    { spanish: 'Comería', russian: 'Я бы ел', topic: 'Condicional Simple' },
    { spanish: 'Hablarías', russian: 'Ты бы говорил', topic: 'Condicional Simple' },
    { spanish: 'Viviría', russian: 'Он/Она бы жил(а)', topic: 'Condicional Simple' },
    { spanish: 'Si tuviera tiempo', russian: 'Если бы у меня было время', topic: 'Condicional' },
    { spanish: 'Que yo comiera', russian: 'Чтобы я ел (прош.)', topic: 'Subjuntivo Imperfecto' },
    { spanish: 'Que tú hablaras', russian: 'Чтобы ты говорил', topic: 'Subjuntivo Imperfecto' },
    { spanish: 'Que él viviera', russian: 'Чтобы он жил', topic: 'Subjuntivo Imperfecto' },
    { spanish: 'Aunque', russian: 'Хотя', topic: 'Союзы' },
    { spanish: 'A pesar de que', russian: 'Несмотря на то, что', topic: 'Союзы' },
    { spanish: 'Con tal de que', russian: 'При условии, что', topic: 'Союзы' },
    { spanish: 'La globalización', russian: 'Глобализация', topic: 'Общество' },
    { spanish: 'Los derechos humanos', russian: 'Права человека', topic: 'Общество' },
    { spanish: 'La inmigración', russian: 'Иммиграция', topic: 'Общество' },
    { spanish: 'El desarrollo sostenible', russian: 'Устойчивое развитие', topic: 'Экология' },
    { spanish: 'Las energías renovables', russian: 'Возобновляемая энергия', topic: 'Экология' },
    { spanish: 'El cambio climático', russian: 'Изменение климата', topic: 'Экология' },
    { spanish: 'La innovación', russian: 'Инновация', topic: 'Наука' },
    { spanish: 'La investigación', russian: 'Исследование', topic: 'Наука' },
    { spanish: 'El descubrimiento', russian: 'Открытие', topic: 'Наука' },
  ],
  'C1': [
    { spanish: 'Había comido', russian: 'Я уже поел (предпрошедшее)', topic: 'Pluscuamperfecto' },
    { spanish: 'Habías hablado', russian: 'Ты уже говорил', topic: 'Pluscuamperfecto' },
    { spanish: 'Había vivido', russian: 'Он/Она уже жил(а)', topic: 'Pluscuamperfecto' },
    { spanish: 'Habré comido', russian: 'Я поем (будущее завершённое)', topic: 'Futuro Perfecto' },
    { spanish: 'Habrás hablado', russian: 'Ты будешь говорить', topic: 'Futuro Perfecto' },
    { spanish: 'Habrá vivido', russian: 'Он/Она будет жить', topic: 'Futuro Perfecto' },
    { spanish: 'La retórica', russian: 'Риторика', topic: 'Лингвистика' },
    { spanish: 'La argumentación', russian: 'Аргументация', topic: 'Академическое' },
    { spanish: 'El análisis crítico', russian: 'Критический анализ', topic: 'Академическое' },
    { spanish: 'La metodología', russian: 'Методология', topic: 'Наука' },
    { spanish: 'La hipótesis', russian: 'Гипотеза', topic: 'Наука' },
    { spanish: 'La tesis', russian: 'Тезис/Диссертация', topic: 'Академическое' },
    { spanish: 'El discurso', russian: 'Дискурс/Речь', topic: 'Лингвистика' },
    { spanish: 'La semiótica', russian: 'Семиотика', topic: 'Лингвистика' },
    { spanish: 'El paradigma', russian: 'Парадигма', topic: 'Философия' },
    { spanish: 'La epistemología', russian: 'Эпистемология', topic: 'Философия' },
  ]
}

// Грамматические темы для каждого уровня
export const GRAMMAR_TOPICS_BY_LEVEL: Record<CEFRLevel, string[]> = {
  'Базовый': [
    'Алфавит испанского языка',
    'Правила чтения и произношения',
    'Ударение в словах',
    'Артикли: el, la, los, las',
    'Род существительных',
    'Множественное число существительных',
    'Личные местоимения',
    'Вопросительные слова: ¿Qué? ¿Quién? ¿Dónde?',
    'Числа от 0 до 100',
    'Базовые фразы и выражения',
  ],
  'A1': [
    'Presente de Indicativo: глаголы -ar',
    'Presente de Indicativo: глаголы -er',
    'Presente de Indicativo: глаголы -ir',
    'Глагол SER (быть/являться)',
    'Глагол ESTAR (находиться/быть)',
    'Различие между SER и ESTAR',
    'Глагол TENER (иметь)',
    'Глагол HABER (быть, существовать) - HAY',
    'Возвратные глаголы (-se)',
    'Притяжательные местоимения (mi, tu, su)',
    'Указательные местоимения (este, ese, aquel)',
    'Предлоги места (en, sobre, bajo)',
    'Предлоги времени (a, de, desde, hasta)',
    'Наречия частоты (siempre, nunca, a veces)',
  ],
  'A2': [
    'Pretérito Perfecto (he comido)',
    'Pretérito Indefinido (comí)',
    'Различие Perfecto vs Indefinido',
    'Причастия неправильных глаголов',
    'Степени сравнения прилагательных',
    'Превосходная степень (el más... de)',
    'Конструкция IR A + инфинитив (будущее)',
    'Безличные глаголы (gustar, encantar, doler)',
    'Глаголы изменения (ponerse, hacerse, volverse)',
    'Ser vs Estar в прошедшем времени',
  ],
  'B1': [
    'Pretérito Imperfecto (comía)',
    'Различие Indefinido vs Imperfecto',
    'Futuro Simple (comeré)',
    'Subjuntivo Presente: формы',
    'Subjuntivo: после глаголов желания',
    'Subjuntivo: после глаголов сомнения',
    'Subjuntivo: после безличных конструкций',
    'Imperativo утвердительный',
    'Imperativo отрицательный',
    'Por vs Para',
  ],
  'B2': [
    'Condicional Simple (comería)',
    'Subjuntivo Imperfecto (comiera)',
    'Условные предложения II типа',
    'Условные предложения III типа',
    'Subjuntivo в придаточных времени',
    'Subjuntivo в уступительных придаточных',
    'Subjuntivo в придаточных цели',
    'Косвенная речь в прошедшем',
    'Согласование времён',
  ],
  'C1': [
    'Pluscuamperfecto (había comido)',
    'Futuro Perfecto (habré comido)',
    'Condicional Perfecto (habría comido)',
    'Subjuntivo Perfecto (haya comido)',
    'Subjuntivo Pluscuamperfecto (hubiera comido)',
    'Сложные условные предложения',
    'Пассивный залог (ser + participio)',
    'Пассивная конструкция с SE',
    'Перифразы с инфинитивом',
    'Перифразы с герундием',
  ]
}

// Темы для чтения по уровням
export const READING_TOPICS_BY_LEVEL: Record<CEFRLevel, string[]> = {
  'Базовый': [
    'Mi familia (Моя семья)',
    'Mi casa (Мой дом)',
    'Un día típico (Типичный день)',
    'Los colores (Цвета)',
    'Los animales (Животные)',
  ],
  'A1': [
    'Presentación personal (Личное представление)',
    'Mi familia y yo (Моя семья и я)',
    'Mi rutina diaria (Моя ежедневная рутина)',
    'En el restaurante (В ресторане)',
    'De compras (За покупками)',
    'El fin de semana (Выходные)',
    'Mis aficiones (Мои увлечения)',
  ],
  'A2': [
    'Mis últimas vacaciones (Мои последние каникулы)',
    'Una experiencia inolvidable (Незабываемый опыт)',
    'La ciudad donde vivo (Город, где я живу)',
    'El clima y las estaciones (Климат и времена года)',
    'Planes para el futuro (Планы на будущее)',
  ],
  'B1': [
    'La importancia del medio ambiente (Важность окружающей среды)',
    'La tecnología en nuestras vidas (Технологии в нашей жизни)',
    'Tradiciones españolas (Испанские традиции)',
    'El mundo laboral (Мир труда)',
  ],
  'B2': [
    'La globalización: ventajas e inconvenientes (Глобализация: плюсы и минусы)',
    'El cambio climático (Изменение климата)',
    'Los derechos humanos (Права человека)',
    'La inmigración en el siglo XXI (Иммиграция в XXI веке)',
  ],
  'C1': [
    'El análisis del discurso político (Анализ политического дискурса)',
    'La retórica en la literatura española (Риторика в испанской литературе)',
    'Teorías filosóficas contemporáneas (Современные философские теории)',
    'La investigación científica moderna (Современные научные исследования)',
  ]
}
